Checks for canvas before trying to remove it
We have been seeing front-end errors reporting:

TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
  at.componentWillUnmount (https://isaacphysics.org/...

This should fix that but I have not determined the true cause to reproduce.